### ISSUE TITLE
task list

### ISSUE THREAD

**Issue by MO1-dot-618** [MO1-dot-618/markdown-portfolio#2]
- [x] create task list
- [ ] turn on github pages
- [ ]  add headers
- [ ] merge headers
- [ ] add image
- [ ] add profile link
- [ ] merge image and link
- [ ] add list
- [ ] use emphasis
- [ ] merge lists and emphasis
